# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': '\u51fa\u7248\u793e'},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(verbose_name='\u7f51\u5740'),
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
    ]
