# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170720_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': '\u51fa\u7248\u793e', 'verbose_name_plural': '\u51fa\u7248\u793e'},
        ),
    ]
